seed : 0

datasetFolder : "cifar-10"
datasetClasses : ['airplane', 'ship', 'automobile', 'frog', 'horse']
dataSplit : 0.8

batchSize : 64

trainModel : False
numEpochs : 7
learningRate : 0.01

testModel : True

saveFolder : "baselinePretrained"
loadModel : True

loss : "CrossEntropyLossWithSoftMax"
ModelType : 0